# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3fdc39de4417518d7e749c2ca3e878ba56486fcdbbe0de6fb0e9670bf642861807378917ef77e56ae12994afccc5ad11f88a12869fa84fdbdd21900d68b144a

test:
  secret_key_base: 1010fc103c1e332183f89dad24d1e6a6a2cf25ce8f1d7cc75ad1092288b071ee0a2cc3293cebacaccc5aaea9d948c8279c997d1cc5ee6dedf642d89216c60a61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
